### ISSUE TITLE
Where i can get the TOKEN?

### ISSUE THREAD

**Issue by alibaltschun** [Daniel-EST/dota2gsipy#3]
what TOKEN did i need?
is that from valve web?

**Comment by alibaltschun** [comment]
i just not read the README properly,

so as long as the the token in cfg and py file same, it will be work right

**Comment by Daniel-EST** [comment]
Did you manage to use the library correctly on your system? Some users have reported issues recently, but I haven't had the time to investigate thoroughly and address them.

**Comment by alibaltschun** [comment]
The last light i use for detecting clock_time and it works.

but you need to update the README, coz we need to edit Dota property too on Steam
https://support.overwolf.com/en/support/solutions/articles/9000212745-how-to-enable-game-state-integration-for-dota-2

the only problem was when I wanted to terminate the process (CTRL+C) on the terminal. it is not closed properly.
so I need close there terminal, reopen same directory, change code. test again. close terminal again.

i already try using try catch etc etc to terminate the process. but it did not work. i don't know why

**Comment by Daniel-EST** [comment]
> The last light i use for detecting clock_time and it works.
> 
> but you need to update the README, coz we need to edit Dota property too on Steam https://support.overwolf.com/en/support/solutions/articles/9000212745-how-to-enable-game-state-integration-for-dota-2

While I was researching to create this library, I came across a [Dota 2 changelog](https://store.steampowered.com/news/app/570/view/4491783379124370818) that mentioned the need for it. However, another user informed me that it was no longer necessary. Unfortunately, I couldn't verify this at the time (see Issue #2 ).

> 
> the only problem was when I wanted to terminate the process (CTRL+C) on the terminal. it is not closed properly. so I need close there terminal, reopen same directory, change code. test again. close terminal again.
> 
> i already try using try catch etc etc to terminate the process. but it did not work. i don't know why

It is a problem with how errors are handled in the library. It is indeed a undesirable behavior that I plan on fixing.
